import esbuild from "esbuild";
import process from "node:process";
import path from "node:path";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
Source lives in the src/ directory of the Placeholder Manager repository.
*/`;

const prod = process.argv[2] === "production";

const productionPlugins = prod
  ? [
      {
        name: "strip-development-invariants",
        setup(build) {
          build.onResolve(
            { filter: /dev-invariants$/ },
            () => ({
              path: path.resolve("src/dev-invariants.production.ts"),
            }),
          );
        },
      },
    ]
  : [];
const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  plugins: productionPlugins,
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2021",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  define: {
    __PLACEHOLDER_DEV_ASSERTIONS__: prod ? "false" : "true",
  },
  outfile: "main.js",
  minify: prod,
});

if (prod) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
